### ISSUE TITLE
Generate new line character after all tests are complete

### ISSUE THREAD

**Issue by qlonik** [evanliomain/karma-super-dots-reporter#1]
Hello.

Whenever this reporter is included in gulp, the gulp logger prints on the same line as reported test runs. Also, it might interfere with other reporters and other reporters might start printing on the same line.

```
√√√√√√√√√√√√√√[12:00:00] 'test' 
```

Thanks.

**Comment by whyboris** [comment]
I second this suggestion. [My reporter](https://github.com/whyboris/karma-helpful-reporter) gets messed up thus:

![image](https://user-images.githubusercontent.com/17264277/39199888-94dafba0-47b8-11e8-9818-05043a9b8300.png)
