### ISSUE TITLE
Suppress failed test error stacktrace from appearing

### ISSUE THREAD

**Issue by whyboris** [evanliomain/karma-super-dots-reporter#2]
I love this reporter!
Is it possible for a reporter to suppress the stack trace from appearing when an error occurs? 
I have a [separate reporter](https://github.com/whyboris/karma-helpful-reporter) that pretty-prints my errors at the end once all the tests have run. I don't want the standard output showing up during the time `super-dots` is running, see example below:

![image](https://user-images.githubusercontent.com/17264277/39199691-1828d1ae-47b8-11e8-9bfb-28e6cc66ea6f.png)

Is it possible to have a setting that simply suppresses these default stacktrace printouts?

**Comment by evanliomain** [comment]
@whyboris This reporter does not log any stack trace.
It seems to be your separate reporter which log that.
To avoid this behavior, It should be report all errors and stack trace at the end of tests run.

**Comment by whyboris** [comment]
Thank you for the response! I'll try to figure out what is doing it 😀
